/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BodyLoginForAccessTokenApiV1AuthLoginPost,
  HTTPValidationError,
  User,
  UserAccessToken,
  UserCreate,
} from "../model";

import { queryFetch } from "../../query-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create User
 */
export type createUserApiV1AuthUsersPostResponse200 = {
  data: User;
  status: 200;
};

export type createUserApiV1AuthUsersPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createUserApiV1AuthUsersPostResponseSuccess =
  createUserApiV1AuthUsersPostResponse200 & {
    headers: Headers;
  };
export type createUserApiV1AuthUsersPostResponseError =
  createUserApiV1AuthUsersPostResponse422 & {
    headers: Headers;
  };

export type createUserApiV1AuthUsersPostResponse =
  | createUserApiV1AuthUsersPostResponseSuccess
  | createUserApiV1AuthUsersPostResponseError;

export const getCreateUserApiV1AuthUsersPostUrl = () => {
  return `/api/v1/auth/users`;
};

export const createUserApiV1AuthUsersPost = async (
  userCreate: UserCreate,
  options?: RequestInit
): Promise<createUserApiV1AuthUsersPostResponse> => {
  return queryFetch<createUserApiV1AuthUsersPostResponse>(
    getCreateUserApiV1AuthUsersPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userCreate),
    }
  );
};

export const getCreateUserApiV1AuthUsersPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createUserApiV1AuthUsersPost>>,
    TError,
    { data: UserCreate },
    TContext
  >;
  request?: SecondParameter<typeof queryFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createUserApiV1AuthUsersPost>>,
  TError,
  { data: UserCreate },
  TContext
> => {
  const mutationKey = ["createUserApiV1AuthUsersPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createUserApiV1AuthUsersPost>>,
    { data: UserCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createUserApiV1AuthUsersPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateUserApiV1AuthUsersPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createUserApiV1AuthUsersPost>>
>;
export type CreateUserApiV1AuthUsersPostMutationBody = UserCreate;
export type CreateUserApiV1AuthUsersPostMutationError = HTTPValidationError;

/**
 * @summary Create User
 */
export const useCreateUserApiV1AuthUsersPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createUserApiV1AuthUsersPost>>,
      TError,
      { data: UserCreate },
      TContext
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createUserApiV1AuthUsersPost>>,
  TError,
  { data: UserCreate },
  TContext
> => {
  return useMutation(
    getCreateUserApiV1AuthUsersPostMutationOptions(options),
    queryClient
  );
};
/**
 * @summary Login For Access Token
 */
export type loginForAccessTokenApiV1AuthLoginPostResponse200 = {
  data: UserAccessToken;
  status: 200;
};

export type loginForAccessTokenApiV1AuthLoginPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type loginForAccessTokenApiV1AuthLoginPostResponseSuccess =
  loginForAccessTokenApiV1AuthLoginPostResponse200 & {
    headers: Headers;
  };
export type loginForAccessTokenApiV1AuthLoginPostResponseError =
  loginForAccessTokenApiV1AuthLoginPostResponse422 & {
    headers: Headers;
  };

export type loginForAccessTokenApiV1AuthLoginPostResponse =
  | loginForAccessTokenApiV1AuthLoginPostResponseSuccess
  | loginForAccessTokenApiV1AuthLoginPostResponseError;

export const getLoginForAccessTokenApiV1AuthLoginPostUrl = () => {
  return `/api/v1/auth/login`;
};

export const loginForAccessTokenApiV1AuthLoginPost = async (
  bodyLoginForAccessTokenApiV1AuthLoginPost: BodyLoginForAccessTokenApiV1AuthLoginPost,
  options?: RequestInit
): Promise<loginForAccessTokenApiV1AuthLoginPostResponse> => {
  const formUrlEncoded = new URLSearchParams();
  if (
    bodyLoginForAccessTokenApiV1AuthLoginPost.grant_type !== undefined &&
    bodyLoginForAccessTokenApiV1AuthLoginPost.grant_type !== null
  ) {
    formUrlEncoded.append(
      `grant_type`,
      bodyLoginForAccessTokenApiV1AuthLoginPost.grant_type
    );
  }
  formUrlEncoded.append(
    `username`,
    bodyLoginForAccessTokenApiV1AuthLoginPost.username
  );
  formUrlEncoded.append(
    `password`,
    bodyLoginForAccessTokenApiV1AuthLoginPost.password
  );
  if (bodyLoginForAccessTokenApiV1AuthLoginPost.scope !== undefined) {
    formUrlEncoded.append(
      `scope`,
      bodyLoginForAccessTokenApiV1AuthLoginPost.scope
    );
  }
  if (
    bodyLoginForAccessTokenApiV1AuthLoginPost.client_id !== undefined &&
    bodyLoginForAccessTokenApiV1AuthLoginPost.client_id !== null
  ) {
    formUrlEncoded.append(
      `client_id`,
      bodyLoginForAccessTokenApiV1AuthLoginPost.client_id
    );
  }
  if (
    bodyLoginForAccessTokenApiV1AuthLoginPost.client_secret !== undefined &&
    bodyLoginForAccessTokenApiV1AuthLoginPost.client_secret !== null
  ) {
    formUrlEncoded.append(
      `client_secret`,
      bodyLoginForAccessTokenApiV1AuthLoginPost.client_secret
    );
  }

  return queryFetch<loginForAccessTokenApiV1AuthLoginPostResponse>(
    getLoginForAccessTokenApiV1AuthLoginPostUrl(),
    {
      ...options,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options?.headers,
      },
      body: formUrlEncoded,
    }
  );
};

export const getLoginForAccessTokenApiV1AuthLoginPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginForAccessTokenApiV1AuthLoginPost>>,
    TError,
    { data: BodyLoginForAccessTokenApiV1AuthLoginPost },
    TContext
  >;
  request?: SecondParameter<typeof queryFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginForAccessTokenApiV1AuthLoginPost>>,
  TError,
  { data: BodyLoginForAccessTokenApiV1AuthLoginPost },
  TContext
> => {
  const mutationKey = ["loginForAccessTokenApiV1AuthLoginPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginForAccessTokenApiV1AuthLoginPost>>,
    { data: BodyLoginForAccessTokenApiV1AuthLoginPost }
  > = (props) => {
    const { data } = props ?? {};

    return loginForAccessTokenApiV1AuthLoginPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginForAccessTokenApiV1AuthLoginPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginForAccessTokenApiV1AuthLoginPost>>
>;
export type LoginForAccessTokenApiV1AuthLoginPostMutationBody =
  BodyLoginForAccessTokenApiV1AuthLoginPost;
export type LoginForAccessTokenApiV1AuthLoginPostMutationError =
  HTTPValidationError;

/**
 * @summary Login For Access Token
 */
export const useLoginForAccessTokenApiV1AuthLoginPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginForAccessTokenApiV1AuthLoginPost>>,
      TError,
      { data: BodyLoginForAccessTokenApiV1AuthLoginPost },
      TContext
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof loginForAccessTokenApiV1AuthLoginPost>>,
  TError,
  { data: BodyLoginForAccessTokenApiV1AuthLoginPost },
  TContext
> => {
  return useMutation(
    getLoginForAccessTokenApiV1AuthLoginPostMutationOptions(options),
    queryClient
  );
};
/**
 * @summary Get Current User
 */
export type getCurrentUserApiV1AuthUsersMeGetResponse200 = {
  data: User;
  status: 200;
};

export type getCurrentUserApiV1AuthUsersMeGetResponseSuccess =
  getCurrentUserApiV1AuthUsersMeGetResponse200 & {
    headers: Headers;
  };
export type getCurrentUserApiV1AuthUsersMeGetResponse =
  getCurrentUserApiV1AuthUsersMeGetResponseSuccess;

export const getGetCurrentUserApiV1AuthUsersMeGetUrl = () => {
  return `/api/v1/auth/users/me`;
};

export const getCurrentUserApiV1AuthUsersMeGet = async (
  options?: RequestInit
): Promise<getCurrentUserApiV1AuthUsersMeGetResponse> => {
  return queryFetch<getCurrentUserApiV1AuthUsersMeGetResponse>(
    getGetCurrentUserApiV1AuthUsersMeGetUrl(),
    {
      ...options,
      method: "GET",
    }
  );
};

export const getGetCurrentUserApiV1AuthUsersMeGetQueryKey = () => {
  return [`/api/v1/auth/users/me`] as const;
};

export const getGetCurrentUserApiV1AuthUsersMeGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof queryFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCurrentUserApiV1AuthUsersMeGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>
  > = ({ signal }) =>
    getCurrentUserApiV1AuthUsersMeGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserApiV1AuthUsersMeGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>
>;
export type GetCurrentUserApiV1AuthUsersMeGetQueryError = unknown;

export function useGetCurrentUserApiV1AuthUsersMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUserApiV1AuthUsersMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUserApiV1AuthUsersMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Current User
 */

export function useGetCurrentUserApiV1AuthUsersMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetCurrentUserApiV1AuthUsersMeGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
