/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChatCreate,
  ChatGet,
  CreateChatApiV1ChatPostParams,
  CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams,
  HTTPValidationError,
  MessageGet,
} from "../model";

import { queryFetch } from "../../query-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Create a new chat.
 * @summary Create Chat
 */
export type createChatApiV1ChatPostResponse200 = {
  data: ChatCreate;
  status: 200;
};

export type createChatApiV1ChatPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createChatApiV1ChatPostResponseSuccess =
  createChatApiV1ChatPostResponse200 & {
    headers: Headers;
  };
export type createChatApiV1ChatPostResponseError =
  createChatApiV1ChatPostResponse422 & {
    headers: Headers;
  };

export type createChatApiV1ChatPostResponse =
  | createChatApiV1ChatPostResponseSuccess
  | createChatApiV1ChatPostResponseError;

export const getCreateChatApiV1ChatPostUrl = (
  params: CreateChatApiV1ChatPostParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/chat/?${stringifiedParams}`
    : `/api/v1/chat/`;
};

export const createChatApiV1ChatPost = async (
  params: CreateChatApiV1ChatPostParams,
  options?: RequestInit
): Promise<createChatApiV1ChatPostResponse> => {
  return queryFetch<createChatApiV1ChatPostResponse>(
    getCreateChatApiV1ChatPostUrl(params),
    {
      ...options,
      method: "POST",
    }
  );
};

export const getCreateChatApiV1ChatPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
    TError,
    { params: CreateChatApiV1ChatPostParams },
    TContext
  >;
  request?: SecondParameter<typeof queryFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
  TError,
  { params: CreateChatApiV1ChatPostParams },
  TContext
> => {
  const mutationKey = ["createChatApiV1ChatPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
    { params: CreateChatApiV1ChatPostParams }
  > = (props) => {
    const { params } = props ?? {};

    return createChatApiV1ChatPost(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateChatApiV1ChatPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createChatApiV1ChatPost>>
>;

export type CreateChatApiV1ChatPostMutationError = HTTPValidationError;

/**
 * @summary Create Chat
 */
export const useCreateChatApiV1ChatPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
      TError,
      { params: CreateChatApiV1ChatPostParams },
      TContext
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
  TError,
  { params: CreateChatApiV1ChatPostParams },
  TContext
> => {
  return useMutation(
    getCreateChatApiV1ChatPostMutationOptions(options),
    queryClient
  );
};
/**
 * @summary Get Chats
 */
export type getChatsApiV1ChatAllGetResponse200 = {
  data: ChatGet[];
  status: 200;
};

export type getChatsApiV1ChatAllGetResponseSuccess =
  getChatsApiV1ChatAllGetResponse200 & {
    headers: Headers;
  };
export type getChatsApiV1ChatAllGetResponse =
  getChatsApiV1ChatAllGetResponseSuccess;

export const getGetChatsApiV1ChatAllGetUrl = () => {
  return `/api/v1/chat/all`;
};

export const getChatsApiV1ChatAllGet = async (
  options?: RequestInit
): Promise<getChatsApiV1ChatAllGetResponse> => {
  return queryFetch<getChatsApiV1ChatAllGetResponse>(
    getGetChatsApiV1ChatAllGetUrl(),
    {
      ...options,
      method: "GET",
    }
  );
};

export const getGetChatsApiV1ChatAllGetQueryKey = () => {
  return [`/api/v1/chat/all`] as const;
};

export const getGetChatsApiV1ChatAllGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof queryFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetChatsApiV1ChatAllGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>
  > = ({ signal }) => getChatsApiV1ChatAllGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChatsApiV1ChatAllGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>
>;
export type GetChatsApiV1ChatAllGetQueryError = unknown;

export function useGetChatsApiV1ChatAllGet<
  TData = Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
          TError,
          Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatsApiV1ChatAllGet<
  TData = Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
          TError,
          Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatsApiV1ChatAllGet<
  TData = Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Chats
 */

export function useGetChatsApiV1ChatAllGet<
  TData = Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChatsApiV1ChatAllGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Chat Messages
 */
export type getChatMessagesApiV1ChatChatIdMessagesGetResponse200 = {
  data: unknown[];
  status: 200;
};

export type getChatMessagesApiV1ChatChatIdMessagesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getChatMessagesApiV1ChatChatIdMessagesGetResponseSuccess =
  getChatMessagesApiV1ChatChatIdMessagesGetResponse200 & {
    headers: Headers;
  };
export type getChatMessagesApiV1ChatChatIdMessagesGetResponseError =
  getChatMessagesApiV1ChatChatIdMessagesGetResponse422 & {
    headers: Headers;
  };

export type getChatMessagesApiV1ChatChatIdMessagesGetResponse =
  | getChatMessagesApiV1ChatChatIdMessagesGetResponseSuccess
  | getChatMessagesApiV1ChatChatIdMessagesGetResponseError;

export const getGetChatMessagesApiV1ChatChatIdMessagesGetUrl = (
  chatId: number
) => {
  return `/api/v1/chat/${chatId}/messages`;
};

export const getChatMessagesApiV1ChatChatIdMessagesGet = async (
  chatId: number,
  options?: RequestInit
): Promise<getChatMessagesApiV1ChatChatIdMessagesGetResponse> => {
  return queryFetch<getChatMessagesApiV1ChatChatIdMessagesGetResponse>(
    getGetChatMessagesApiV1ChatChatIdMessagesGetUrl(chatId),
    {
      ...options,
      method: "GET",
    }
  );
};

export const getGetChatMessagesApiV1ChatChatIdMessagesGetQueryKey = (
  chatId: number
) => {
  return [`/api/v1/chat/${chatId}/messages`] as const;
};

export const getGetChatMessagesApiV1ChatChatIdMessagesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
  TError = HTTPValidationError,
>(
  chatId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetChatMessagesApiV1ChatChatIdMessagesGetQueryKey(chatId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>
  > = ({ signal }) =>
    getChatMessagesApiV1ChatChatIdMessagesGet(chatId, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!chatId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChatMessagesApiV1ChatChatIdMessagesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>
>;
export type GetChatMessagesApiV1ChatChatIdMessagesGetQueryError =
  HTTPValidationError;

export function useGetChatMessagesApiV1ChatChatIdMessagesGet<
  TData = Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
  TError = HTTPValidationError,
>(
  chatId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
          TError,
          Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatMessagesApiV1ChatChatIdMessagesGet<
  TData = Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
  TError = HTTPValidationError,
>(
  chatId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
          TError,
          Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatMessagesApiV1ChatChatIdMessagesGet<
  TData = Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
  TError = HTTPValidationError,
>(
  chatId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Chat Messages
 */

export function useGetChatMessagesApiV1ChatChatIdMessagesGet<
  TData = Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
  TError = HTTPValidationError,
>(
  chatId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChatMessagesApiV1ChatChatIdMessagesGetQueryOptions(
    chatId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Chat Message
 */
export type getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse200 = {
  data: MessageGet;
  status: 200;
};

export type getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponseSuccess =
  getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse200 & {
    headers: Headers;
  };
export type getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponseError =
  getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse422 & {
    headers: Headers;
  };

export type getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse =
  | getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponseSuccess
  | getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponseError;

export const getGetChatMessageApiV1ChatChatIdMessagesMessageIdGetUrl = (
  chatId: number,
  messageId: number
) => {
  return `/api/v1/chat/${chatId}/messages/${messageId}`;
};

export const getChatMessageApiV1ChatChatIdMessagesMessageIdGet = async (
  chatId: number,
  messageId: number,
  options?: RequestInit
): Promise<getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse> => {
  return queryFetch<getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse>(
    getGetChatMessageApiV1ChatChatIdMessagesMessageIdGetUrl(chatId, messageId),
    {
      ...options,
      method: "GET",
    }
  );
};

export const getGetChatMessageApiV1ChatChatIdMessagesMessageIdGetQueryKey = (
  chatId: number,
  messageId: number
) => {
  return [`/api/v1/chat/${chatId}/messages/${messageId}`] as const;
};

export const getGetChatMessageApiV1ChatChatIdMessagesMessageIdGetQueryOptions =
  <
    TData = Awaited<
      ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
    >,
    TError = HTTPValidationError,
  >(
    chatId: number,
    messageId: number,
    options?: {
      query?: Partial<
        UseQueryOptions<
          Awaited<
            ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
          >,
          TError,
          TData
        >
      >;
      request?: SecondParameter<typeof queryFetch>;
    }
  ) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getGetChatMessageApiV1ChatChatIdMessagesMessageIdGetQueryKey(
        chatId,
        messageId
      );

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
      >
    > = ({ signal }) =>
      getChatMessageApiV1ChatChatIdMessagesMessageIdGet(chatId, messageId, {
        signal,
        ...requestOptions,
      });

    return {
      queryKey,
      queryFn,
      enabled: !!(chatId && messageId),
      ...queryOptions,
    } as UseQueryOptions<
      Awaited<
        ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
      >,
      TError,
      TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
  };

export type GetChatMessageApiV1ChatChatIdMessagesMessageIdGetQueryResult =
  NonNullable<
    Awaited<
      ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
    >
  >;
export type GetChatMessageApiV1ChatChatIdMessagesMessageIdGetQueryError =
  HTTPValidationError;

export function useGetChatMessageApiV1ChatChatIdMessagesMessageIdGet<
  TData = Awaited<
    ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
  >,
  TError = HTTPValidationError,
>(
  chatId: number,
  messageId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
          >,
          TError,
          Awaited<
            ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatMessageApiV1ChatChatIdMessagesMessageIdGet<
  TData = Awaited<
    ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
  >,
  TError = HTTPValidationError,
>(
  chatId: number,
  messageId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
          >,
          TError,
          Awaited<
            ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatMessageApiV1ChatChatIdMessagesMessageIdGet<
  TData = Awaited<
    ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
  >,
  TError = HTTPValidationError,
>(
  chatId: number,
  messageId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Chat Message
 */

export function useGetChatMessageApiV1ChatChatIdMessagesMessageIdGet<
  TData = Awaited<
    ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
  >,
  TError = HTTPValidationError,
>(
  chatId: number,
  messageId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetChatMessageApiV1ChatChatIdMessagesMessageIdGetQueryOptions(
      chatId,
      messageId,
      options
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create Pahalx Response
 */
export type createPahalxResponseApiV1ChatChatChatIdResponsePostResponse200 = {
  data: unknown;
  status: 200;
};

export type createPahalxResponseApiV1ChatChatChatIdResponsePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createPahalxResponseApiV1ChatChatChatIdResponsePostResponseSuccess =
  createPahalxResponseApiV1ChatChatChatIdResponsePostResponse200 & {
    headers: Headers;
  };
export type createPahalxResponseApiV1ChatChatChatIdResponsePostResponseError =
  createPahalxResponseApiV1ChatChatChatIdResponsePostResponse422 & {
    headers: Headers;
  };

export type createPahalxResponseApiV1ChatChatChatIdResponsePostResponse =
  | createPahalxResponseApiV1ChatChatChatIdResponsePostResponseSuccess
  | createPahalxResponseApiV1ChatChatChatIdResponsePostResponseError;

export const getCreatePahalxResponseApiV1ChatChatChatIdResponsePostUrl = (
  chatId: number,
  params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/chat/chat/${chatId}/response?${stringifiedParams}`
    : `/api/v1/chat/chat/${chatId}/response`;
};

export const createPahalxResponseApiV1ChatChatChatIdResponsePost = async (
  chatId: number,
  params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams,
  options?: RequestInit
): Promise<createPahalxResponseApiV1ChatChatChatIdResponsePostResponse> => {
  return queryFetch<createPahalxResponseApiV1ChatChatChatIdResponsePostResponse>(
    getCreatePahalxResponseApiV1ChatChatChatIdResponsePostUrl(chatId, params),
    {
      ...options,
      method: "POST",
    }
  );
};

export const getCreatePahalxResponseApiV1ChatChatChatIdResponsePostMutationOptions =
  <TError = HTTPValidationError, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof createPahalxResponseApiV1ChatChatChatIdResponsePost>
      >,
      TError,
      {
        chatId: number;
        params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams;
      },
      TContext
    >;
    request?: SecondParameter<typeof queryFetch>;
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof createPahalxResponseApiV1ChatChatChatIdResponsePost>
    >,
    TError,
    {
      chatId: number;
      params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams;
    },
    TContext
  > => {
    const mutationKey = ["createPahalxResponseApiV1ChatChatChatIdResponsePost"];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof createPahalxResponseApiV1ChatChatChatIdResponsePost>
      >,
      {
        chatId: number;
        params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams;
      }
    > = (props) => {
      const { chatId, params } = props ?? {};

      return createPahalxResponseApiV1ChatChatChatIdResponsePost(
        chatId,
        params,
        requestOptions
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type CreatePahalxResponseApiV1ChatChatChatIdResponsePostMutationResult =
  NonNullable<
    Awaited<
      ReturnType<typeof createPahalxResponseApiV1ChatChatChatIdResponsePost>
    >
  >;

export type CreatePahalxResponseApiV1ChatChatChatIdResponsePostMutationError =
  HTTPValidationError;

/**
 * @summary Create Pahalx Response
 */
export const useCreatePahalxResponseApiV1ChatChatChatIdResponsePost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof createPahalxResponseApiV1ChatChatChatIdResponsePost>
      >,
      TError,
      {
        chatId: number;
        params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams;
      },
      TContext
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<
    ReturnType<typeof createPahalxResponseApiV1ChatChatChatIdResponsePost>
  >,
  TError,
  {
    chatId: number;
    params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams;
  },
  TContext
> => {
  return useMutation(
    getCreatePahalxResponseApiV1ChatChatChatIdResponsePostMutationOptions(
      options
    ),
    queryClient
  );
};
