/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BodyLoginForAccessTokenApiV1AuthLoginPost,
  ChatCreate,
  ChatGet,
  CreateChatApiV1ChatPostParams,
  CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams,
  HTTPValidationError,
  MessageGet,
  TypedHTTPExceptionModelAuthErrorCode,
  TypedHTTPExceptionModelChatErrorCode,
  User,
  UserAccessToken,
  UserCreate,
} from "./model";

import { queryFetch } from "../query-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create User
 */
export type createUserApiV1AuthUsersPostResponse200 = {
  data: User;
  status: 200;
};

export type createUserApiV1AuthUsersPostResponse400 = {
  data: TypedHTTPExceptionModelAuthErrorCode;
  status: 400;
};

export type createUserApiV1AuthUsersPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createUserApiV1AuthUsersPostResponseSuccess =
  createUserApiV1AuthUsersPostResponse200 & {
    headers: Headers;
  };
export type createUserApiV1AuthUsersPostResponseError = (
  | createUserApiV1AuthUsersPostResponse400
  | createUserApiV1AuthUsersPostResponse422
) & {
  headers: Headers;
};

export const getCreateUserApiV1AuthUsersPostUrl = () => {
  return `/api/v1/auth/users`;
};

export const createUserApiV1AuthUsersPost = async (
  userCreate: UserCreate,
  options?: RequestInit
): Promise<createUserApiV1AuthUsersPostResponseSuccess> => {
  return queryFetch<createUserApiV1AuthUsersPostResponseSuccess>(
    getCreateUserApiV1AuthUsersPostUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(userCreate),
    }
  );
};

export const getCreateUserApiV1AuthUsersPostMutationOptions = <
  TError = TypedHTTPExceptionModelAuthErrorCode | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createUserApiV1AuthUsersPost>>,
    TError,
    { data: UserCreate },
    TContext
  >;
  request?: SecondParameter<typeof queryFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createUserApiV1AuthUsersPost>>,
  TError,
  { data: UserCreate },
  TContext
> => {
  const mutationKey = ["createUserApiV1AuthUsersPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createUserApiV1AuthUsersPost>>,
    { data: UserCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createUserApiV1AuthUsersPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateUserApiV1AuthUsersPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createUserApiV1AuthUsersPost>>
>;
export type CreateUserApiV1AuthUsersPostMutationBody = UserCreate;
export type CreateUserApiV1AuthUsersPostMutationError =
  | TypedHTTPExceptionModelAuthErrorCode
  | HTTPValidationError;

/**
 * @summary Create User
 */
export const useCreateUserApiV1AuthUsersPost = <
  TError = TypedHTTPExceptionModelAuthErrorCode | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createUserApiV1AuthUsersPost>>,
      TError,
      { data: UserCreate },
      TContext
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createUserApiV1AuthUsersPost>>,
  TError,
  { data: UserCreate },
  TContext
> => {
  return useMutation(
    getCreateUserApiV1AuthUsersPostMutationOptions(options),
    queryClient
  );
};

/**
 * @summary Login For Access Token
 */
export type loginForAccessTokenApiV1AuthLoginPostResponse200 = {
  data: UserAccessToken;
  status: 200;
};

export type loginForAccessTokenApiV1AuthLoginPostResponse401 = {
  data: TypedHTTPExceptionModelAuthErrorCode;
  status: 401;
};

export type loginForAccessTokenApiV1AuthLoginPostResponse404 = {
  data: TypedHTTPExceptionModelAuthErrorCode;
  status: 404;
};

export type loginForAccessTokenApiV1AuthLoginPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type loginForAccessTokenApiV1AuthLoginPostResponseSuccess =
  loginForAccessTokenApiV1AuthLoginPostResponse200 & {
    headers: Headers;
  };
export type loginForAccessTokenApiV1AuthLoginPostResponseError = (
  | loginForAccessTokenApiV1AuthLoginPostResponse401
  | loginForAccessTokenApiV1AuthLoginPostResponse404
  | loginForAccessTokenApiV1AuthLoginPostResponse422
) & {
  headers: Headers;
};

export const getLoginForAccessTokenApiV1AuthLoginPostUrl = () => {
  return `/api/v1/auth/login`;
};

export const loginForAccessTokenApiV1AuthLoginPost = async (
  bodyLoginForAccessTokenApiV1AuthLoginPost: BodyLoginForAccessTokenApiV1AuthLoginPost,
  options?: RequestInit
): Promise<loginForAccessTokenApiV1AuthLoginPostResponseSuccess> => {
  const formUrlEncoded = new URLSearchParams();
  if (
    bodyLoginForAccessTokenApiV1AuthLoginPost.grant_type !== undefined &&
    bodyLoginForAccessTokenApiV1AuthLoginPost.grant_type !== null
  ) {
    formUrlEncoded.append(
      `grant_type`,
      bodyLoginForAccessTokenApiV1AuthLoginPost.grant_type
    );
  }
  formUrlEncoded.append(
    `username`,
    bodyLoginForAccessTokenApiV1AuthLoginPost.username
  );
  formUrlEncoded.append(
    `password`,
    bodyLoginForAccessTokenApiV1AuthLoginPost.password
  );
  if (bodyLoginForAccessTokenApiV1AuthLoginPost.scope !== undefined) {
    formUrlEncoded.append(
      `scope`,
      bodyLoginForAccessTokenApiV1AuthLoginPost.scope
    );
  }
  if (
    bodyLoginForAccessTokenApiV1AuthLoginPost.client_id !== undefined &&
    bodyLoginForAccessTokenApiV1AuthLoginPost.client_id !== null
  ) {
    formUrlEncoded.append(
      `client_id`,
      bodyLoginForAccessTokenApiV1AuthLoginPost.client_id
    );
  }
  if (
    bodyLoginForAccessTokenApiV1AuthLoginPost.client_secret !== undefined &&
    bodyLoginForAccessTokenApiV1AuthLoginPost.client_secret !== null
  ) {
    formUrlEncoded.append(
      `client_secret`,
      bodyLoginForAccessTokenApiV1AuthLoginPost.client_secret
    );
  }

  return queryFetch<loginForAccessTokenApiV1AuthLoginPostResponseSuccess>(
    getLoginForAccessTokenApiV1AuthLoginPostUrl(),
    {
      ...options,
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options?.headers,
      },
      body: formUrlEncoded,
    }
  );
};

export const getLoginForAccessTokenApiV1AuthLoginPostMutationOptions = <
  TError = TypedHTTPExceptionModelAuthErrorCode | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginForAccessTokenApiV1AuthLoginPost>>,
    TError,
    { data: BodyLoginForAccessTokenApiV1AuthLoginPost },
    TContext
  >;
  request?: SecondParameter<typeof queryFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginForAccessTokenApiV1AuthLoginPost>>,
  TError,
  { data: BodyLoginForAccessTokenApiV1AuthLoginPost },
  TContext
> => {
  const mutationKey = ["loginForAccessTokenApiV1AuthLoginPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginForAccessTokenApiV1AuthLoginPost>>,
    { data: BodyLoginForAccessTokenApiV1AuthLoginPost }
  > = (props) => {
    const { data } = props ?? {};

    return loginForAccessTokenApiV1AuthLoginPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginForAccessTokenApiV1AuthLoginPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginForAccessTokenApiV1AuthLoginPost>>
>;
export type LoginForAccessTokenApiV1AuthLoginPostMutationBody =
  BodyLoginForAccessTokenApiV1AuthLoginPost;
export type LoginForAccessTokenApiV1AuthLoginPostMutationError =
  | TypedHTTPExceptionModelAuthErrorCode
  | HTTPValidationError;

/**
 * @summary Login For Access Token
 */
export const useLoginForAccessTokenApiV1AuthLoginPost = <
  TError = TypedHTTPExceptionModelAuthErrorCode | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loginForAccessTokenApiV1AuthLoginPost>>,
      TError,
      { data: BodyLoginForAccessTokenApiV1AuthLoginPost },
      TContext
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof loginForAccessTokenApiV1AuthLoginPost>>,
  TError,
  { data: BodyLoginForAccessTokenApiV1AuthLoginPost },
  TContext
> => {
  return useMutation(
    getLoginForAccessTokenApiV1AuthLoginPostMutationOptions(options),
    queryClient
  );
};

/**
 * @summary Get Current User
 */
export type getCurrentUserApiV1AuthUsersMeGetResponse200 = {
  data: User;
  status: 200;
};

export type getCurrentUserApiV1AuthUsersMeGetResponse401 = {
  data: TypedHTTPExceptionModelAuthErrorCode;
  status: 401;
};

export type getCurrentUserApiV1AuthUsersMeGetResponseSuccess =
  getCurrentUserApiV1AuthUsersMeGetResponse200 & {
    headers: Headers;
  };
export type getCurrentUserApiV1AuthUsersMeGetResponseError =
  getCurrentUserApiV1AuthUsersMeGetResponse401 & {
    headers: Headers;
  };

export const getGetCurrentUserApiV1AuthUsersMeGetUrl = () => {
  return `/api/v1/auth/users/me`;
};

export const getCurrentUserApiV1AuthUsersMeGet = async (
  options?: RequestInit
): Promise<getCurrentUserApiV1AuthUsersMeGetResponseSuccess> => {
  return queryFetch<getCurrentUserApiV1AuthUsersMeGetResponseSuccess>(
    getGetCurrentUserApiV1AuthUsersMeGetUrl(),
    {
      ...options,
      method: "GET",
    }
  );
};

export const getGetCurrentUserApiV1AuthUsersMeGetQueryKey = () => {
  return [`/api/v1/auth/users/me`] as const;
};

export const getGetCurrentUserApiV1AuthUsersMeGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
  TError = TypedHTTPExceptionModelAuthErrorCode,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof queryFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCurrentUserApiV1AuthUsersMeGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>
  > = ({ signal }) =>
    getCurrentUserApiV1AuthUsersMeGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserApiV1AuthUsersMeGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>
>;
export type GetCurrentUserApiV1AuthUsersMeGetQueryError =
  TypedHTTPExceptionModelAuthErrorCode;

export function useGetCurrentUserApiV1AuthUsersMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
  TError = TypedHTTPExceptionModelAuthErrorCode,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUserApiV1AuthUsersMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
  TError = TypedHTTPExceptionModelAuthErrorCode,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUserApiV1AuthUsersMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
  TError = TypedHTTPExceptionModelAuthErrorCode,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Current User
 */

export function useGetCurrentUserApiV1AuthUsersMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
  TError = TypedHTTPExceptionModelAuthErrorCode,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserApiV1AuthUsersMeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetCurrentUserApiV1AuthUsersMeGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create a new chat.
 * @summary Create Chat
 */
export type createChatApiV1ChatPostResponse200 = {
  data: ChatCreate;
  status: 200;
};

export type createChatApiV1ChatPostResponse401 = {
  data: TypedHTTPExceptionModelAuthErrorCode;
  status: 401;
};

export type createChatApiV1ChatPostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createChatApiV1ChatPostResponseSuccess =
  createChatApiV1ChatPostResponse200 & {
    headers: Headers;
  };
export type createChatApiV1ChatPostResponseError = (
  | createChatApiV1ChatPostResponse401
  | createChatApiV1ChatPostResponse422
) & {
  headers: Headers;
};

export const getCreateChatApiV1ChatPostUrl = (
  params: CreateChatApiV1ChatPostParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/chat/?${stringifiedParams}`
    : `/api/v1/chat/`;
};

export const createChatApiV1ChatPost = async (
  params: CreateChatApiV1ChatPostParams,
  options?: RequestInit
): Promise<createChatApiV1ChatPostResponseSuccess> => {
  return queryFetch<createChatApiV1ChatPostResponseSuccess>(
    getCreateChatApiV1ChatPostUrl(params),
    {
      ...options,
      method: "POST",
    }
  );
};

export const getCreateChatApiV1ChatPostMutationOptions = <
  TError = TypedHTTPExceptionModelAuthErrorCode | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
    TError,
    { params: CreateChatApiV1ChatPostParams },
    TContext
  >;
  request?: SecondParameter<typeof queryFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
  TError,
  { params: CreateChatApiV1ChatPostParams },
  TContext
> => {
  const mutationKey = ["createChatApiV1ChatPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
    { params: CreateChatApiV1ChatPostParams }
  > = (props) => {
    const { params } = props ?? {};

    return createChatApiV1ChatPost(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateChatApiV1ChatPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createChatApiV1ChatPost>>
>;

export type CreateChatApiV1ChatPostMutationError =
  | TypedHTTPExceptionModelAuthErrorCode
  | HTTPValidationError;

/**
 * @summary Create Chat
 */
export const useCreateChatApiV1ChatPost = <
  TError = TypedHTTPExceptionModelAuthErrorCode | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
      TError,
      { params: CreateChatApiV1ChatPostParams },
      TContext
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createChatApiV1ChatPost>>,
  TError,
  { params: CreateChatApiV1ChatPostParams },
  TContext
> => {
  return useMutation(
    getCreateChatApiV1ChatPostMutationOptions(options),
    queryClient
  );
};

/**
 * @summary Delete Chat
 */
export type deleteChatApiV1ChatChatIdDeleteResponse200 = {
  data: unknown;
  status: 200;
};

export type deleteChatApiV1ChatChatIdDeleteResponse401 = {
  data: TypedHTTPExceptionModelAuthErrorCode;
  status: 401;
};

export type deleteChatApiV1ChatChatIdDeleteResponse404 = {
  data: TypedHTTPExceptionModelChatErrorCode;
  status: 404;
};

export type deleteChatApiV1ChatChatIdDeleteResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type deleteChatApiV1ChatChatIdDeleteResponseSuccess =
  deleteChatApiV1ChatChatIdDeleteResponse200 & {
    headers: Headers;
  };
export type deleteChatApiV1ChatChatIdDeleteResponseError = (
  | deleteChatApiV1ChatChatIdDeleteResponse401
  | deleteChatApiV1ChatChatIdDeleteResponse404
  | deleteChatApiV1ChatChatIdDeleteResponse422
) & {
  headers: Headers;
};

export const getDeleteChatApiV1ChatChatIdDeleteUrl = (chatId: number) => {
  return `/api/v1/chat/${chatId}`;
};

export const deleteChatApiV1ChatChatIdDelete = async (
  chatId: number,
  options?: RequestInit
): Promise<deleteChatApiV1ChatChatIdDeleteResponseSuccess> => {
  return queryFetch<deleteChatApiV1ChatChatIdDeleteResponseSuccess>(
    getDeleteChatApiV1ChatChatIdDeleteUrl(chatId),
    {
      ...options,
      method: "DELETE",
    }
  );
};

export const getDeleteChatApiV1ChatChatIdDeleteMutationOptions = <
  TError =
    | TypedHTTPExceptionModelAuthErrorCode
    | TypedHTTPExceptionModelChatErrorCode
    | HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteChatApiV1ChatChatIdDelete>>,
    TError,
    { chatId: number },
    TContext
  >;
  request?: SecondParameter<typeof queryFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteChatApiV1ChatChatIdDelete>>,
  TError,
  { chatId: number },
  TContext
> => {
  const mutationKey = ["deleteChatApiV1ChatChatIdDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteChatApiV1ChatChatIdDelete>>,
    { chatId: number }
  > = (props) => {
    const { chatId } = props ?? {};

    return deleteChatApiV1ChatChatIdDelete(chatId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteChatApiV1ChatChatIdDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteChatApiV1ChatChatIdDelete>>
>;

export type DeleteChatApiV1ChatChatIdDeleteMutationError =
  | TypedHTTPExceptionModelAuthErrorCode
  | TypedHTTPExceptionModelChatErrorCode
  | HTTPValidationError;

/**
 * @summary Delete Chat
 */
export const useDeleteChatApiV1ChatChatIdDelete = <
  TError =
    | TypedHTTPExceptionModelAuthErrorCode
    | TypedHTTPExceptionModelChatErrorCode
    | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteChatApiV1ChatChatIdDelete>>,
      TError,
      { chatId: number },
      TContext
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof deleteChatApiV1ChatChatIdDelete>>,
  TError,
  { chatId: number },
  TContext
> => {
  return useMutation(
    getDeleteChatApiV1ChatChatIdDeleteMutationOptions(options),
    queryClient
  );
};

/**
 * @summary Get Chats
 */
export type getChatsApiV1ChatAllGetResponse200 = {
  data: ChatGet[];
  status: 200;
};

export type getChatsApiV1ChatAllGetResponse401 = {
  data: TypedHTTPExceptionModelAuthErrorCode;
  status: 401;
};

export type getChatsApiV1ChatAllGetResponseSuccess =
  getChatsApiV1ChatAllGetResponse200 & {
    headers: Headers;
  };
export type getChatsApiV1ChatAllGetResponseError =
  getChatsApiV1ChatAllGetResponse401 & {
    headers: Headers;
  };

export const getGetChatsApiV1ChatAllGetUrl = () => {
  return `/api/v1/chat/all`;
};

export const getChatsApiV1ChatAllGet = async (
  options?: RequestInit
): Promise<getChatsApiV1ChatAllGetResponseSuccess> => {
  return queryFetch<getChatsApiV1ChatAllGetResponseSuccess>(
    getGetChatsApiV1ChatAllGetUrl(),
    {
      ...options,
      method: "GET",
    }
  );
};

export const getGetChatsApiV1ChatAllGetQueryKey = () => {
  return [`/api/v1/chat/all`] as const;
};

export const getGetChatsApiV1ChatAllGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
  TError = TypedHTTPExceptionModelAuthErrorCode,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof queryFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetChatsApiV1ChatAllGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>
  > = ({ signal }) => getChatsApiV1ChatAllGet({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChatsApiV1ChatAllGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>
>;
export type GetChatsApiV1ChatAllGetQueryError =
  TypedHTTPExceptionModelAuthErrorCode;

export function useGetChatsApiV1ChatAllGet<
  TData = Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
  TError = TypedHTTPExceptionModelAuthErrorCode,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
          TError,
          Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatsApiV1ChatAllGet<
  TData = Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
  TError = TypedHTTPExceptionModelAuthErrorCode,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
          TError,
          Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatsApiV1ChatAllGet<
  TData = Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
  TError = TypedHTTPExceptionModelAuthErrorCode,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Chats
 */

export function useGetChatsApiV1ChatAllGet<
  TData = Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
  TError = TypedHTTPExceptionModelAuthErrorCode,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatsApiV1ChatAllGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChatsApiV1ChatAllGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Chat Messages
 */
export type getChatMessagesApiV1ChatChatIdMessagesGetResponse200 = {
  data: MessageGet[];
  status: 200;
};

export type getChatMessagesApiV1ChatChatIdMessagesGetResponse401 = {
  data: TypedHTTPExceptionModelAuthErrorCode;
  status: 401;
};

export type getChatMessagesApiV1ChatChatIdMessagesGetResponse404 = {
  data: TypedHTTPExceptionModelChatErrorCode;
  status: 404;
};

export type getChatMessagesApiV1ChatChatIdMessagesGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getChatMessagesApiV1ChatChatIdMessagesGetResponseSuccess =
  getChatMessagesApiV1ChatChatIdMessagesGetResponse200 & {
    headers: Headers;
  };
export type getChatMessagesApiV1ChatChatIdMessagesGetResponseError = (
  | getChatMessagesApiV1ChatChatIdMessagesGetResponse401
  | getChatMessagesApiV1ChatChatIdMessagesGetResponse404
  | getChatMessagesApiV1ChatChatIdMessagesGetResponse422
) & {
  headers: Headers;
};

export const getGetChatMessagesApiV1ChatChatIdMessagesGetUrl = (
  chatId: number
) => {
  return `/api/v1/chat/${chatId}/messages`;
};

export const getChatMessagesApiV1ChatChatIdMessagesGet = async (
  chatId: number,
  options?: RequestInit
): Promise<getChatMessagesApiV1ChatChatIdMessagesGetResponseSuccess> => {
  return queryFetch<getChatMessagesApiV1ChatChatIdMessagesGetResponseSuccess>(
    getGetChatMessagesApiV1ChatChatIdMessagesGetUrl(chatId),
    {
      ...options,
      method: "GET",
    }
  );
};

export const getGetChatMessagesApiV1ChatChatIdMessagesGetQueryKey = (
  chatId: number
) => {
  return [`/api/v1/chat/${chatId}/messages`] as const;
};

export const getGetChatMessagesApiV1ChatChatIdMessagesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
  TError =
    | TypedHTTPExceptionModelAuthErrorCode
    | TypedHTTPExceptionModelChatErrorCode
    | HTTPValidationError,
>(
  chatId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetChatMessagesApiV1ChatChatIdMessagesGetQueryKey(chatId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>
  > = ({ signal }) =>
    getChatMessagesApiV1ChatChatIdMessagesGet(chatId, {
      signal,
      ...requestOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!chatId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChatMessagesApiV1ChatChatIdMessagesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>
>;
export type GetChatMessagesApiV1ChatChatIdMessagesGetQueryError =
  | TypedHTTPExceptionModelAuthErrorCode
  | TypedHTTPExceptionModelChatErrorCode
  | HTTPValidationError;

export function useGetChatMessagesApiV1ChatChatIdMessagesGet<
  TData = Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
  TError =
    | TypedHTTPExceptionModelAuthErrorCode
    | TypedHTTPExceptionModelChatErrorCode
    | HTTPValidationError,
>(
  chatId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
          TError,
          Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatMessagesApiV1ChatChatIdMessagesGet<
  TData = Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
  TError =
    | TypedHTTPExceptionModelAuthErrorCode
    | TypedHTTPExceptionModelChatErrorCode
    | HTTPValidationError,
>(
  chatId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
          TError,
          Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatMessagesApiV1ChatChatIdMessagesGet<
  TData = Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
  TError =
    | TypedHTTPExceptionModelAuthErrorCode
    | TypedHTTPExceptionModelChatErrorCode
    | HTTPValidationError,
>(
  chatId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Chat Messages
 */

export function useGetChatMessagesApiV1ChatChatIdMessagesGet<
  TData = Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
  TError =
    | TypedHTTPExceptionModelAuthErrorCode
    | TypedHTTPExceptionModelChatErrorCode
    | HTTPValidationError,
>(
  chatId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getChatMessagesApiV1ChatChatIdMessagesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetChatMessagesApiV1ChatChatIdMessagesGetQueryOptions(
    chatId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get Chat Message
 */
export type getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse200 = {
  data: MessageGet;
  status: 200;
};

export type getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse401 = {
  data: TypedHTTPExceptionModelAuthErrorCode;
  status: 401;
};

export type getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse404 = {
  data: TypedHTTPExceptionModelChatErrorCode;
  status: 404;
};

export type getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponseSuccess =
  getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse200 & {
    headers: Headers;
  };
export type getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponseError = (
  | getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse401
  | getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse404
  | getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponse422
) & {
  headers: Headers;
};

export const getGetChatMessageApiV1ChatChatIdMessagesMessageIdGetUrl = (
  chatId: number,
  messageId: number
) => {
  return `/api/v1/chat/${chatId}/messages/${messageId}`;
};

export const getChatMessageApiV1ChatChatIdMessagesMessageIdGet = async (
  chatId: number,
  messageId: number,
  options?: RequestInit
): Promise<getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponseSuccess> => {
  return queryFetch<getChatMessageApiV1ChatChatIdMessagesMessageIdGetResponseSuccess>(
    getGetChatMessageApiV1ChatChatIdMessagesMessageIdGetUrl(chatId, messageId),
    {
      ...options,
      method: "GET",
    }
  );
};

export const getGetChatMessageApiV1ChatChatIdMessagesMessageIdGetQueryKey = (
  chatId: number,
  messageId: number
) => {
  return [`/api/v1/chat/${chatId}/messages/${messageId}`] as const;
};

export const getGetChatMessageApiV1ChatChatIdMessagesMessageIdGetQueryOptions =
  <
    TData = Awaited<
      ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
    >,
    TError =
      | TypedHTTPExceptionModelAuthErrorCode
      | TypedHTTPExceptionModelChatErrorCode
      | HTTPValidationError,
  >(
    chatId: number,
    messageId: number,
    options?: {
      query?: Partial<
        UseQueryOptions<
          Awaited<
            ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
          >,
          TError,
          TData
        >
      >;
      request?: SecondParameter<typeof queryFetch>;
    }
  ) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getGetChatMessageApiV1ChatChatIdMessagesMessageIdGetQueryKey(
        chatId,
        messageId
      );

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
      >
    > = ({ signal }) =>
      getChatMessageApiV1ChatChatIdMessagesMessageIdGet(chatId, messageId, {
        signal,
        ...requestOptions,
      });

    return {
      queryKey,
      queryFn,
      enabled: !!(chatId && messageId),
      ...queryOptions,
    } as UseQueryOptions<
      Awaited<
        ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
      >,
      TError,
      TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
  };

export type GetChatMessageApiV1ChatChatIdMessagesMessageIdGetQueryResult =
  NonNullable<
    Awaited<
      ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
    >
  >;
export type GetChatMessageApiV1ChatChatIdMessagesMessageIdGetQueryError =
  | TypedHTTPExceptionModelAuthErrorCode
  | TypedHTTPExceptionModelChatErrorCode
  | HTTPValidationError;

export function useGetChatMessageApiV1ChatChatIdMessagesMessageIdGet<
  TData = Awaited<
    ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
  >,
  TError =
    | TypedHTTPExceptionModelAuthErrorCode
    | TypedHTTPExceptionModelChatErrorCode
    | HTTPValidationError,
>(
  chatId: number,
  messageId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
          >,
          TError,
          Awaited<
            ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatMessageApiV1ChatChatIdMessagesMessageIdGet<
  TData = Awaited<
    ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
  >,
  TError =
    | TypedHTTPExceptionModelAuthErrorCode
    | TypedHTTPExceptionModelChatErrorCode
    | HTTPValidationError,
>(
  chatId: number,
  messageId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
          >,
          TError,
          Awaited<
            ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChatMessageApiV1ChatChatIdMessagesMessageIdGet<
  TData = Awaited<
    ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
  >,
  TError =
    | TypedHTTPExceptionModelAuthErrorCode
    | TypedHTTPExceptionModelChatErrorCode
    | HTTPValidationError,
>(
  chatId: number,
  messageId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Chat Message
 */

export function useGetChatMessageApiV1ChatChatIdMessagesMessageIdGet<
  TData = Awaited<
    ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
  >,
  TError =
    | TypedHTTPExceptionModelAuthErrorCode
    | TypedHTTPExceptionModelChatErrorCode
    | HTTPValidationError,
>(
  chatId: number,
  messageId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getChatMessageApiV1ChatChatIdMessagesMessageIdGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetChatMessageApiV1ChatChatIdMessagesMessageIdGetQueryOptions(
      chatId,
      messageId,
      options
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create Pahalx Response
 */
export type createPahalxResponseApiV1ChatChatChatIdResponsePostResponse200 = {
  data: unknown;
  status: 200;
};

export type createPahalxResponseApiV1ChatChatChatIdResponsePostResponse401 = {
  data: TypedHTTPExceptionModelAuthErrorCode;
  status: 401;
};

export type createPahalxResponseApiV1ChatChatChatIdResponsePostResponse422 = {
  data: HTTPValidationError;
  status: 422;
};

export type createPahalxResponseApiV1ChatChatChatIdResponsePostResponseSuccess =
  createPahalxResponseApiV1ChatChatChatIdResponsePostResponse200 & {
    headers: Headers;
  };
export type createPahalxResponseApiV1ChatChatChatIdResponsePostResponseError = (
  | createPahalxResponseApiV1ChatChatChatIdResponsePostResponse401
  | createPahalxResponseApiV1ChatChatChatIdResponsePostResponse422
) & {
  headers: Headers;
};

export const getCreatePahalxResponseApiV1ChatChatChatIdResponsePostUrl = (
  chatId: number,
  params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/chat/chat/${chatId}/response?${stringifiedParams}`
    : `/api/v1/chat/chat/${chatId}/response`;
};

export const createPahalxResponseApiV1ChatChatChatIdResponsePost = async (
  chatId: number,
  params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams,
  options?: RequestInit
): Promise<createPahalxResponseApiV1ChatChatChatIdResponsePostResponseSuccess> => {
  return queryFetch<createPahalxResponseApiV1ChatChatChatIdResponsePostResponseSuccess>(
    getCreatePahalxResponseApiV1ChatChatChatIdResponsePostUrl(chatId, params),
    {
      ...options,
      method: "POST",
    }
  );
};

export const getCreatePahalxResponseApiV1ChatChatChatIdResponsePostMutationOptions =
  <
    TError = TypedHTTPExceptionModelAuthErrorCode | HTTPValidationError,
    TContext = unknown,
  >(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof createPahalxResponseApiV1ChatChatChatIdResponsePost>
      >,
      TError,
      {
        chatId: number;
        params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams;
      },
      TContext
    >;
    request?: SecondParameter<typeof queryFetch>;
  }): UseMutationOptions<
    Awaited<
      ReturnType<typeof createPahalxResponseApiV1ChatChatChatIdResponsePost>
    >,
    TError,
    {
      chatId: number;
      params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams;
    },
    TContext
  > => {
    const mutationKey = ["createPahalxResponseApiV1ChatChatChatIdResponsePost"];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof createPahalxResponseApiV1ChatChatChatIdResponsePost>
      >,
      {
        chatId: number;
        params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams;
      }
    > = (props) => {
      const { chatId, params } = props ?? {};

      return createPahalxResponseApiV1ChatChatChatIdResponsePost(
        chatId,
        params,
        requestOptions
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type CreatePahalxResponseApiV1ChatChatChatIdResponsePostMutationResult =
  NonNullable<
    Awaited<
      ReturnType<typeof createPahalxResponseApiV1ChatChatChatIdResponsePost>
    >
  >;

export type CreatePahalxResponseApiV1ChatChatChatIdResponsePostMutationError =
  | TypedHTTPExceptionModelAuthErrorCode
  | HTTPValidationError;

/**
 * @summary Create Pahalx Response
 */
export const useCreatePahalxResponseApiV1ChatChatChatIdResponsePost = <
  TError = TypedHTTPExceptionModelAuthErrorCode | HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof createPahalxResponseApiV1ChatChatChatIdResponsePost>
      >,
      TError,
      {
        chatId: number;
        params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams;
      },
      TContext
    >;
    request?: SecondParameter<typeof queryFetch>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<
    ReturnType<typeof createPahalxResponseApiV1ChatChatChatIdResponsePost>
  >,
  TError,
  {
    chatId: number;
    params: CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams;
  },
  TContext
> => {
  return useMutation(
    getCreatePahalxResponseApiV1ChatChatChatIdResponsePostMutationOptions(
      options
    ),
    queryClient
  );
};
