// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CheckUsernameExistsApiV1AuthUsersUsernameGetData, CheckUsernameExistsApiV1AuthUsersUsernameGetErrors, CheckUsernameExistsApiV1AuthUsersUsernameGetResponses, CreateUserApiV1AuthUsersPostData, CreateUserApiV1AuthUsersPostErrors, CreateUserApiV1AuthUsersPostResponses, LoginApiV1AuthLoginPostData, LoginApiV1AuthLoginPostErrors, LoginApiV1AuthLoginPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create User
 */
export const createUserApiV1AuthUsersPost = <ThrowOnError extends boolean = false>(options: Options<CreateUserApiV1AuthUsersPostData, ThrowOnError>) => (options.client ?? client).post<CreateUserApiV1AuthUsersPostResponses, CreateUserApiV1AuthUsersPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Check Username Exists
 */
export const checkUsernameExistsApiV1AuthUsersUsernameGet = <ThrowOnError extends boolean = false>(options: Options<CheckUsernameExistsApiV1AuthUsersUsernameGetData, ThrowOnError>) => (options.client ?? client).get<CheckUsernameExistsApiV1AuthUsersUsernameGetResponses, CheckUsernameExistsApiV1AuthUsersUsernameGetErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/users/{username}',
    ...options
});

/**
 * Login
 */
export const loginApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiV1AuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<LoginApiV1AuthLoginPostResponses, LoginApiV1AuthLoginPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/login',
    ...options
});
