// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type Options as Options2, type TDataShape, urlSearchParamsBodySerializer } from './client';
import { client } from './client.gen';
import type { CreateUserApiV1AuthUsersPostData, CreateUserApiV1AuthUsersPostErrors, CreateUserApiV1AuthUsersPostResponses, GetCurrentUserApiV1AuthUsersMeGetData, GetCurrentUserApiV1AuthUsersMeGetResponses, LoginForAccessTokenApiV1AuthLoginPostData, LoginForAccessTokenApiV1AuthLoginPostErrors, LoginForAccessTokenApiV1AuthLoginPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Create User
 */
export const createUserApiV1AuthUsersPost = <ThrowOnError extends boolean = false>(options: Options<CreateUserApiV1AuthUsersPostData, ThrowOnError>) => (options.client ?? client).post<CreateUserApiV1AuthUsersPostResponses, CreateUserApiV1AuthUsersPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/auth/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login For Access Token
 */
export const loginForAccessTokenApiV1AuthLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginForAccessTokenApiV1AuthLoginPostData, ThrowOnError>) => (options.client ?? client).post<LoginForAccessTokenApiV1AuthLoginPostResponses, LoginForAccessTokenApiV1AuthLoginPostErrors, ThrowOnError>({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        ...options.headers
    }
});

/**
 * Get Current User
 */
export const getCurrentUserApiV1AuthUsersMeGet = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserApiV1AuthUsersMeGetData, ThrowOnError>) => (options?.client ?? client).get<GetCurrentUserApiV1AuthUsersMeGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/api/v1/auth/users/me',
    ...options
});
