// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login_for_access_token_api_v1_auth_login_post
 */
export type BodyLoginForAccessTokenApiV1AuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name: string;
};

/**
 * UserAccessToken
 */
export type UserAccessToken = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type CreateUserApiV1AuthUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users';
};

export type CreateUserApiV1AuthUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1AuthUsersPostError = CreateUserApiV1AuthUsersPostErrors[keyof CreateUserApiV1AuthUsersPostErrors];

export type CreateUserApiV1AuthUsersPostResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type CreateUserApiV1AuthUsersPostResponse = CreateUserApiV1AuthUsersPostResponses[keyof CreateUserApiV1AuthUsersPostResponses];

export type LoginForAccessTokenApiV1AuthLoginPostData = {
    body: BodyLoginForAccessTokenApiV1AuthLoginPost;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type LoginForAccessTokenApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginForAccessTokenApiV1AuthLoginPostError = LoginForAccessTokenApiV1AuthLoginPostErrors[keyof LoginForAccessTokenApiV1AuthLoginPostErrors];

export type LoginForAccessTokenApiV1AuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: UserAccessToken;
};

export type LoginForAccessTokenApiV1AuthLoginPostResponse = LoginForAccessTokenApiV1AuthLoginPostResponses[keyof LoginForAccessTokenApiV1AuthLoginPostResponses];

export type GetCurrentUserApiV1AuthUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users/me';
};

export type GetCurrentUserApiV1AuthUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type GetCurrentUserApiV1AuthUsersMeGetResponse = GetCurrentUserApiV1AuthUsersMeGetResponses[keyof GetCurrentUserApiV1AuthUsersMeGetResponses];
