// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name: string;
    /**
     * Password
     */
    password: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type CreateUserApiV1AuthUsersPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/auth/users';
};

export type CreateUserApiV1AuthUsersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserApiV1AuthUsersPostError = CreateUserApiV1AuthUsersPostErrors[keyof CreateUserApiV1AuthUsersPostErrors];

export type CreateUserApiV1AuthUsersPostResponses = {
    /**
     * Successful Response
     */
    200: User;
};

export type CreateUserApiV1AuthUsersPostResponse = CreateUserApiV1AuthUsersPostResponses[keyof CreateUserApiV1AuthUsersPostResponses];

export type CheckUsernameExistsApiV1AuthUsersUsernameGetData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/api/v1/auth/users/{username}';
};

export type CheckUsernameExistsApiV1AuthUsersUsernameGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckUsernameExistsApiV1AuthUsersUsernameGetError = CheckUsernameExistsApiV1AuthUsersUsernameGetErrors[keyof CheckUsernameExistsApiV1AuthUsersUsernameGetErrors];

export type CheckUsernameExistsApiV1AuthUsersUsernameGetResponses = {
    /**
     * Response Check Username Exists Api V1 Auth Users  Username  Get
     *
     * Successful Response
     */
    200: boolean;
};

export type CheckUsernameExistsApiV1AuthUsersUsernameGetResponse = CheckUsernameExistsApiV1AuthUsersUsernameGetResponses[keyof CheckUsernameExistsApiV1AuthUsersUsernameGetResponses];

export type LoginApiV1AuthLoginPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Username
         */
        username: string;
        /**
         * Password
         */
        password: string;
    };
    url: '/api/v1/auth/login';
};

export type LoginApiV1AuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthLoginPostError = LoginApiV1AuthLoginPostErrors[keyof LoginApiV1AuthLoginPostErrors];

export type LoginApiV1AuthLoginPostResponses = {
    /**
     * Response Login Api V1 Auth Login Post
     *
     * Successful Response
     */
    200: boolean;
};

export type LoginApiV1AuthLoginPostResponse = LoginApiV1AuthLoginPostResponses[keyof LoginApiV1AuthLoginPostResponses];
