/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type AuthErrorCode = (typeof AuthErrorCode)[keyof typeof AuthErrorCode];

export const AuthErrorCode = {
  user_not_found: "user_not_found",
  invalid_credentials: "invalid_credentials",
  token_expired: "token_expired",
  invalid_token: "invalid_token",
  user_already_exists: "user_already_exists",
  unknown_error: "unknown_error",
} as const;
