/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ChatCreate {
  id: number;
  title: string;
  created_at: string;
  updated_at: string;
}
