/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type ChatErrorCode = (typeof ChatErrorCode)[keyof typeof ChatErrorCode];

export const ChatErrorCode = {
  chat_not_found: "chat_not_found",
  message_not_found: "message_not_found",
} as const;
