/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type CreatePahalxResponseApiV1ChatChatChatIdResponsePostParams = {
  user_message: string;
  model?: string;
};
