/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { MessageRole } from "./messageRole";
import type { MessageStatus } from "./messageStatus";

export interface MessageGet {
  id: number;
  chat_id: number;
  role: MessageRole;
  content: string;
  created_at: string;
  status: MessageStatus;
}
