/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type MessageRole = (typeof MessageRole)[keyof typeof MessageRole];

export const MessageRole = {
  system: "system",
  user: "user",
  assistant: "assistant",
} as const;
