/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type MessageStatus = (typeof MessageStatus)[keyof typeof MessageStatus];

export const MessageStatus = {
  streaming: "streaming",
  completed: "completed",
} as const;
