/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { AuthErrorCode } from "./authErrorCode";

export interface TypedHTTPExceptionDetailsAuthErrorCode {
  msg: string;
  code: AuthErrorCode;
}
