/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ChatErrorCode } from "./chatErrorCode";

export interface TypedHTTPExceptionDetailsChatErrorCode {
  msg: string;
  code: ChatErrorCode;
}
